name: quran
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  get: 4.6.6
  http: ^1.2.1
  lottie: ^3.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/lotties/
    - assets/
    
  uses-material-design: true
